---
name: Aypex::Emails CI
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  # POSTGRES
  postgres:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2']

        # Set N number of parallel jobs you want to run tests on.
        # Use higher number if you have slow tests to split them on more parallel jobs.
        # Remember to update ci_node_index below to 0..N-1
        ci_node_total: [1]

        # set N-1 indexes for parallel jobs
        # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
        ci_node_index: [0]

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aypex_emails
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Set up Redis
        uses: shogo82148/actions-setup-redis@v1.19.0

      - name: Install libvips
        run: sudo apt-get install -y libvips

      - name: Make bin/core/ci executable
        run: chmod +x ./bin/ci

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/aypex_emails
          RAILS_ENV: test
          DB: postgresql
          CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          CI_NODE_INDEX: ${{ matrix.ci_node_index }}
        run: |
          bundle exec rake test_app
          ./bin/ci

      - name: Upload failed screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: failed-screenshots
          path: ${{ github.workspace }}/tmp/dummy/tmp/capybara
